openapi: 3.1.0
info:
  title: SeeYouThere API
  version: 1.0.0
  description: >
    Finds the cheapest common destination for a set of travelers flying from different origins.
paths:
  /api/cheapest-destination:
    post:
      summary: Find cheapest common destination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheapestDestinationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheapestDestinationResponse'
components:
  schemas:
    CheapestDestinationRequest:
      type: object
      required: [origins, regionType, regions, date]
      properties:
        origins:
          type: array
          items: { type: string }
        regionType:
          type: string
          enum: [continent, country, countries]
        regions:
          type: array
          items: { type: string }
        date:
          type: string
          format: date
    CheapestDestinationResponse:
      type: object
      properties:
        destinationCity:  { type: string }
        destinationCountry: { type: string }
        totalPrice:      { type: number, format: float }
        currency:        { type: string }