openapi: 3.0.3
info:
  title: SeeYouThere API
  version: 1.0.0
paths:
  /api/cheapest-destination:
    post:
      summary: Find cheapest common destination
      operationId: PostCheapestDestination
      tags: [CheapestDestination]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheapestDestinationRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheapestDestinationResponse'
components:
  schemas:
    CheapestDestinationRequest:
      type: object
      properties:
        origins:
          type: array
          items: { type: string }
        date:
          type: string
          format: date
    CheapestDestinationResponse:
      type: object
      properties:
        destinationCity:  { type: string }
        totalPrice:       { type: number, format: float }
