name: CI/CD

on:
  push:
    branches: [ develop, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Generate OpenAPI Server Code
        run: |
          docker run --rm -v $PWD:/local \
            openapitools/openapi-generator-cli:latest generate \
            -i /local/spec/openapi.yaml \
            -g aspnetcore \
            -o /local/gen/SeeYouThere.Api.Specification \
            --additional-properties=packageName=SeeYouThere.Api.Specification,aspnetCoreVersion=9.0,buildTarget=library,classModifier=abstract,useSwashbuckle=false

      - name: Restore & Build
        run: dotnet build SeeYouThereAPI.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test SeeYouThereAPI.sln --configuration Release --no-build

  docker-publish:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from openapi.yaml
        id: version
        run: |
          VERSION=$(grep '^  version:' spec/openapi.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/seeyouthereapi:latest
            ghcr.io/${{ github.repository_owner }}/seeyouthereapi:${{ steps.version.outputs.version }}
